/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  corePlugins: {
    preflight: false,
  },
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        "brand-blue": "var(--color-blue)",
        "brand-orange": "var(--color-orange)",
        "brand-navy": "var(--color-navy)",
        "outline-variant": "#444653",
        "tertiary-container": "#bb8555",
        "on-tertiary-fixed": "#2e1500",
        "surface-variant": "#2f3445",
        "error-container": "#93000a",
        "on-secondary-fixed": "#0f1a37",
        "on-primary-fixed-variant": "#1f3ba6",
        "on-primary": "#002388",
        outline: "#8f909e",
        "on-background": "#dee1f7",
        "surface-container": "#1a1f2f",
        "on-secondary": "#252f4d",
        "on-surface-variant": "#c5c5d5",
        "surface-container-low": "var(--bg-section)",
        "primary-fixed": "#dde1ff",
        background: "var(--bg-base)",
        secondary: "#bbc5eb",
        "on-secondary-fixed-variant": "#3b4665",
        "on-primary-fixed": "#001356",
        "surface-tint": "#b9c3ff",
        "tertiary-fixed-dim": "#f7ba85",
        "on-secondary-container": "#aab4d9",
        tertiary: "#f7ba85",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#25293a",
        "inverse-surface": "#dee1f7",
        "surface-container-highest": "#2f3445",
        "on-tertiary-fixed-variant": "#663d13",
        "on-primary-container": "#001e78",
        primary: "#b9c3ff",
        "primary-container": "#7189f6",
        "secondary-container": "#3b4665",
        "surface-bright": "#343949",
        "on-error": "#690005",
        "on-surface": "#dee1f7",
        "on-tertiary": "#4c2700",
        surface: "var(--bg-card)",
        error: "#ffb4ab",
        "tertiary-fixed": "#ffdcc1",
        "inverse-on-surface": "#2b3040",
        "secondary-fixed": "#dae1ff",
        "surface-container-lowest": "#090e1c",
        "primary-fixed-dim": "#b9c3ff",
        "surface-dim": "var(--bg-base)",
        "inverse-primary": "#3c55bf",
        "secondary-fixed-dim": "#bbc5eb",
        "on-tertiary-container": "#422200",
      },
      fontFamily: {
        headline: ["Bebas Neue", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        monument: ["Monument Extended", "sans-serif"],
        grotesk: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
